### ISSUE TITLE
travis: tests failing

### ISSUE THREAD

**Issue by broady** [golang/gddo#441]
https://travis-ci.org/golang/gddo/builds/158353337

```
$ ../go_appengine/goapp test -v .
2016/09/08 04:02:53 appengine: not running under devappserver2; using some default configuration
panic: missing GitHub metadata, follow the instructions on README.md
goroutine 1 [running]:
panic(0x8d2320, 0xc8202711b0)
	/home/travis/gopath/src/github.com/golang/gddo/go_appengine/goroot/src/runtime/panic.go:481 +0x3e6
github.com/golang/gddo/talksapp.init.1()
	/home/travis/gopath/src/github.com/golang/gddo/talksapp/main.go:49 +0x29b
github.com/golang/gddo/talksapp.init()
	/home/travis/gopath/src/github.com/golang/gddo/talksapp/main_test.go:236 +0x209
main.init()
	github.com/golang/gddo/talksapp/_test/_testmain.go:68 +0x4a
exit status 2
FAIL	github.com/golang/gddo/talksapp	0.023s
The command "../go_appengine/goapp test -v ." exited with 1.
```

This check should check first for dev app server, or we should put some github credentials into the travis build. I think the former.

**Comment by broady** [comment]
cc @campoy

**Comment by campoy** [comment]
One more CL to fix this
